### ISSUE TITLE
How to override Lando's PHP-FPM settings

### ISSUE THREAD

**Issue by tormi** [lando/php#108]
Here's a recipe for overriding Lando's PHP-FPM settings.

### `.lando.yml`

```yml
services:
  appserver:
    overrides:
      volumes:
        # Override /usr/local/etc/php-fpm.d/www.conf values.
        - ./.lando/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
```

### `.lando/php-fpm.conf`

```cnf
; Override /usr/local/etc/php-fpm.d/www.conf values.
[www]

user = www-data
group = www-data
listen = 127.0.0.1:9000
pm = dynamic
pm.max_children = 50
pm.start_servers = 20
pm.min_spare_servers = 10
pm.max_spare_servers = 20
pm.max_requests = 500
```
