### ISSUE TITLE
Add Imagick to PHP 8.3

### ISSUE THREAD

**Issue by AaronFeledy** [lando/php#114]
Due to an incompatibility issue with Imagick and PHP 8.3, we have deliberately not included the Imagick extension with our 8.3 image. The upstream issue can be tracked at imagick/imagick#640.

Once the bug in imagick is fixed, we should get it added in.

Note that the matrix in extensions.md and the note below the matrix should be updated to reflect this change when it does occur.

**Comment by AaronFeledy** [comment]
Note that the fix has been merged into the develop branch of Imagick but a new release has yet to be rolled out. If you need Imagick in PHP 8.3, you can try installing from the develop source via build steps in your landofile.

```yaml
services:
   appserver:
     build_as_root:
       - mkdir -p /usr/src/php/ext/imagick
       - curl -fsSL https://github.com/Imagick/imagick/archive/28f27044e435a2b203e32675e942eb8de620ee58.tar.gz | tar xvz -C "/usr/src/php/ext/imagick" --strip 1
       - docker-php-ext-install imagick
```
