### ISSUE TITLE
Guidance for how to setup xdebug 3 for a PHP command line tool and VSCode

### ISSUE THREAD

**Issue by yorkshire-pudding** [lando/php#127]
I have Lando running on a Linux (mint 22) PC that also has VSCode on.  I have successfully added and tested XDebug with a Backdrop CMS recipe on the same setup, but using a browser extension to support triggering.

What I have so far (xdebug related) in my test amendments for the recipe for the development and testing of this project (It is [Bee, the command line tool for Backdrop CMS](/backdrop-contrib/bee) ; I am the maintainer of this project) are:

```yaml
config:
  php: 8.3
  xdebug: true
services:
  appserver:
    overrides:
      environment:
        XDEBUG-CONFIG: "start_with_request=yes"
```

My `launch.json` looks like:

```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Listen for XDebug",
        "type": "php",
        "request": "launch",
        "port": 9003,
        "pathMappings": {
          "/app/": "${workspaceFolder}/",
        }
      }
    ]
  }
```
I set a breakpoint and start Listening but nothing appears in the debugger within VSCode. 
I'm sure I must be missing something obvious but I've looked through a number of places and not sure what else I need to do.

I'm only working with PHP 7.4 onwards so don't need to worry about Xdebug 2

Thanks

**Comment by reynoldsalec** [comment]
I would try explicitly setting `xdebug.client_host=${LANDO_HOST_IP}`. It looks like my config for Xdebug 3 is something like this...most of it shouldn't be necessary but for debugging can help to be explicit:

```
xdebug.mode = coverage,develop,debug
xdebug.idekey = docker
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.client_port = 9003
xdebug.start_with_request = yes
xdebug.log = /tmp/xdebug.log
```

**Comment by yorkshire-pudding** [comment]
Thanks for the quick reply @reynoldsalec . Alas, this isn't making a difference with this.
I put this in a `php.ini` within the app folder structure and referred to it in the lando recipe:

```yaml
services:
  appserver:
    config:
      php: /app/.lando/php.ini
```

I hope that is right.

**Comment by reynoldsalec** [comment]
@yorkshire-pudding try referring to the php config relative to the app root

```
services:
  appserver:
    config:
      php: .lando/php.ini
```
