### ISSUE TITLE
Update to the latest GD library

### ISSUE THREAD

**Issue by kaszarobert** [lando/php#166]
When we use Lando with PHP this version is used from the gd library:

```
GD Support | enabled
-- | --
GD Version | bundled (2.1.0 compatible)
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.10.4
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 6b
PNG Support | enabled
libPNG Version | 1.6.37
WBMP Support | enabled
XBM Support | enabled
WebP Support | enabled
BMP Support | enabled
TGA Read Support | enabled
```

Well, this bundled version https://github.com/libgd/libgd/releases/tag/gd-2.1.0 is almost 10 year old.

The latest version is 2.3.3 https://github.com/libgd/libgd/releases

**Comment by AaronFeledy** [comment]
The drupal recipe should be using the latest PHP images. Try a `lando rebuild` to update your app to the latest images.

**Comment by kaszarobert** [comment]
I tried changing PHP versions with `lando rebuild`:

```
name: drupal1083
recipe: drupal10
config:
  webroot: web
  php: '8.4'
  database: mariadb:10.6
  composer_version: '2'
  xdebug: false

```

But still for `lando php -i`:

```
gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.12.1
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.6.39
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled
BMP Support => enabled
AVIF Support => enabled
TGA Read Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => On => On
```

On our other non-Lando production server this is returned and that gd version seems to behave differently in a rare use case when adding text to an image and calculating the font height, that's why I'm wondering if something is not up-to-date here.

```
gd

GD Support => enabled
GD headers Version => 2.3.3
GD library Version => 2.3.3
FreeType Support => enabled
FreeType Linkage => with freetype
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
PNG Support => enabled
WBMP Support => enabled
XPM Support => enabled
XBM Support => enabled
WebP Support => enabled
BMP Support => enabled
AVIF Support => enabled
TGA Read Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```

Are experiencing different results than me for `lando php -i` ?

**Comment by kaszarobert** [comment]
Now that I look at it, the PHP GD extension is fine and up to date. What happens here is that the Lando PHP image does not have a separate libgd library installed but it is using an older GD library that is compiled into PHP if I understand that correctly. So in my case I need to install that library and setup PHP to use that --with-external-gd as they mention here https://www.php.net/manual/en/image.installation.php something like that in the Dockerfile:

```
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev libjpeg-dev libfreetype6-dev libwebp-dev \
    wget

RUN cd /usr/local/src && \
    wget https://github.com/libgd/libgd/releases/download/gd-2.3.3/libgd-2.3.3.tar.gz && \
    tar -xzf libgd-2.3.3.tar.gz && \
    cd libgd-2.3.3 && \
    ./configure --prefix=/usr/local && \
    make && make install

# Then configure PHP GD to use it (be sure paths are correct)
RUN docker-php-ext-configure gd \
    --with-freetype \
    --with-jpeg \
    --with-webp \
    --with-external-gd \
    && docker-php-ext-install gd
```

So I'm not sure if that needs to be the default in the Lando PHP image. If not, we can close this feature request I guess.

**Comment by AaronFeledy** [comment]
Ah, you're correct. We're using the GD that's compiled into PHP, not the one that's provided by the Debian 12 repo. I'll do some research on which versions the big hosting providers are using. If it's later than the bundled version, I'll update Lando's as well.

The workaround for now is to add the above to build steps in your landofile then run a `lando rebuild`.
```yaml
services:
  appserver:
    build_as_root:
      - apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libwebp-dev
      - cd /usr/local/src && wget https://github.com/libgd/libgd/releases/download/gd-2.3.3/libgd-2.3.3.tar.gz
      - tar -xzf libgd-2.3.3.tar.gz && cd libgd-2.3.3 && ./configure --prefix=/usr/local && make && make install
      - docker-php-ext-configure gd && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp --with-external-gd
```
