### ISSUE TITLE
Updating recipe with mysql database to PHP 8.4 causes mysql command errors

### ISSUE THREAD

**Issue by yorkshire-pudding** [lando/php#167]
I have a Backdrop recipe with MySQL database; I have tried with default and `8.0`
It has a setup script that runs some `mysql` commands to create additional databases and grant all privileges to the default database user.
It was previously on PHP 8.3 and this script ran fine.

When it runs now it gives the following error:
```
mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
ERROR 2026 (HY000): TLS/SSL error: self-signed certificate in certificate chain
```

I also get this on `mysqldump`:

```
/usr/bin/mysqldump: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb-dump' instead
mysqldump: Got error: 2026: "TLS/SSL error: Certificate verification failure: The certificate is NOT trusted." when trying to connect
```

I ssh'd into the app to see what is happening:

```
$ lando ssh -u root
root@fc220caa9207:/app# ls -al /usr/bin/mariadb
-rwxr-xr-x 1 root root 5308896 Oct 30  2024 /usr/bin/mariadb
root@fc220caa9207:/app# ls -al /usr/bin/mysql
lrwxrwxrwx 1 root root 7 Oct 30  2024 /usr/bin/mysql -> mariadb
root@fc220caa9207:/app#
```

This doesn't make sense when it is configured for MySQL.  Here is the relevant part of the output from `lando info`:

```yaml
  { service: 'database',
    urls: [],
    type: 'backdrop-mysql',
    healthy: true,
    internal_connection: { host: 'database', port: '3306' },
    external_connection: { host: '127.0.0.1', port: '44787' },
    healthcheck:
     'mysql --defaults-extra-file=/app/.lando/mysql.cnf --silent --execute "SHOW DATABASES;"',
    creds: { database: 'backdrop', password: 'backdrop', user: 'backdrop' },
    config: { database: '/home/shl/.lando/config/backdrop/mysql.cnf' },
    version: '5.7',
    meUser: 'www-data',
    hasCerts: false,
    api: 3,
    hostnames: [ 'database.bee.internal' ],
    hostname: [] },
```

Switching back to PHP 8.3 and they all work. I don't understand this as the command is a linux command not a PHP command.
I have tested with another Backdrop recipe and get the same.

**Comment by AaronFeledy** [comment]
The older PHP 8.3 image probably has a older versions of the mariadb cli tools installed that don't require SSL validation. You might be able to work around it by using the fully qualified name for the host: `database.bee.internal`.

Lando should probably be doing something different here if you're getting errors like this in what should be a common use case. I'm unsure if this is a Lando bug generally, or if you've stumbled upon some errant state with certificates. Can you post some minimal representation of a landofile and a script that will trigger the error so I can see if I can replicate and identify a specific bug on the Lando side?

**Comment by AaronFeledy** [comment]
This might work as a workaround to the cert issue:
```yaml
services:
  appserver:
    build_as_root:
      - echo "[client]\nssl-verify-server-cert = off" > /etc/mysql/mariadb.conf.d/zz-lando.cnf

**Comment by AaronFeledy** [comment]
This should set you up with the MySQL cli tools:
```yaml
services:
  appserver:
    build_as_root:
      - cd /var/www && wget https://dev.mysql.com/get/mysql-apt-config_0.8.34-1_all.deb
      - export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y /var/www/mysql-apt-config_0.8.34-1_all.deb
      - apt update && apt install -y mysql-client
```

**Comment by yorkshire-pudding** [comment]
Thanks @AaronFeledy 
This is a definite improvement though one thing I'm struggling with: using `mysqldump` within the `appserver` I get the following:
```
-- Warning: column statistics not supported by the server.
```

I want to disable this warning at the lando level (it works on other servers) as having output like this can break the tests.

I tried:

```yaml
services:
  appserver:
    build_as_root:
      - echo "[mysqldump]\ncolumn-statistics=0\n" > /etc/mysql/conf.d/zz-lando.cnf
```
and 

```yaml
services:
  appserver:
    build:
      - echo "[mysqldump]\ncolumn-statistics=0\n" > ~/.my.cnf
```

In both cases, the files are created but the error persists. I think there is now a dodgy mix of mariadb and mysql configuration that is stopping it working:

```shell

root@6ef2abdbf29f:/app/backdrop# cd /etc/mysql/
root@6ef2abdbf29f:/etc/mysql# ls -al
total 28
drwxr-xr-x 1 root root 4096 Jun 23 09:23 .
drwxr-xr-x 1 root root 4096 Jun 23 09:23 ..
drwxr-xr-x 1 root root 4096 Jun 23 09:23 conf.d
-rw-r--r-- 1 root root 1126 Oct 30  2024 mariadb.cnf
drwxr-xr-x 2 root root 4096 Jan  8 18:52 mariadb.conf.d
lrwxrwxrwx 1 root root   24 Jan  8 18:52 my.cnf -> /etc/alternatives/my.cnf
root@6ef2abdbf29f:/etc/mysql# ls -al conf.d/
total 16
drwxr-xr-x 1 root root 4096 Jun 23 09:23 .
drwxr-xr-x 1 root root 4096 Jun 23 09:23 ..
-rw-r--r-- 1 root root   32 Jun 23 09:23 zz-lando.cnf
root@6ef2abdbf29f:/etc/mysql# cat my.cnf
# The MariaDB configuration file
#
# The MariaDB/MySQL tools read configuration files in the following order:
# 0. "/etc/mysql/my.cnf" symlinks to this file, reason why all the rest is read.
# 1. "/etc/mysql/mariadb.cnf" (this file) to set global defaults,
# 2. "/etc/mysql/conf.d/*.cnf" to set global options.
# 3. "/etc/mysql/mariadb.conf.d/*.cnf" to set MariaDB-only options.
# 4. "~/.my.cnf" to set user-specific options.
#
# If the same option is defined multiple times, the last one will apply.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# If you are new to MariaDB, check out https://mariadb.com/kb/en/basic-mariadb-articles/

#
# This group is read both by the client and the server
# use it for options that affect everything
#
[client-server]
# Port or socket location where to connect
# port = 3306
socket = /run/mysqld/mysqld.sock

# Import all .cnf files from configuration directory
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/

```

Any ideas how to get the config working correctly?
