### ISSUE TITLE
.htaccess-lando not overriding .htaccess

### ISSUE THREAD

**Issue by web-assistant** [lando/php#38]
I'm trying to override the .htaccess file as instructed in [https://docs.lando.dev/config/apache.html#configuration](url). Adding .htaccess-lando next to the Drupal root .htaccess file doesn't do anything. I have tried rebuilding and also tried adding the custom httpd.conf file taken from [https://github.com/lando/lando/tree/master/plugins/lando-services/services/apache](url). Any ideas how I can get this working?

![screen](https://user-images.githubusercontent.com/5895452/82541063-c77c0b00-9b47-11ea-9958-519f27e47673.png)

Running Lando v3.0.3 on Windows 10.

```
name: thingymajig
recipe: drupal7
config:
  php: '7.2'
  via: apache
  webroot: web
  database: mariadb
  drush: ^8
  xdebug: false
  config:
    php: .lando/.lando.php.ini
    database: .lando/.lando.mysql.cnf
    server: .lando/httpd.conf
    vhosts: .lando/default.conf

proxy:
  appserver:
    - thingymajig.lndo.site
    - www.thingymajig.lndo.site
  mailhog:
    - mail.thingymajig.lndo.site
  pma:
    - pma.thingymajig.lndo.site
  adminer:
    - adminer.thingymajig.lndo.site

services:
  database:
    creds:
      database: thingymajig
      user: thingymabob
      password: easylike123
  appserver:
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
  pma:
    type: phpmyadmin
    hosts:
      - database
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    portforward: true

tooling:
  xon:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xoff:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root

excludes:
  - .idea
  - .git
```
