### ISSUE TITLE
Add PHP 8.3 support

### ISSUE THREAD

**Issue by kaszarobert** [lando/php#77]
[Soon a new version of PHP will be released.](https://wiki.php.net/todo/php83) Although, it is not yet stable but it would be good to add a possibility to use that in Lando even before a stable release.

Until that, we have to use a custom Docker image. Here's what we've been using recently to test out webapps and Drupal sites manually under PHP 8.3 RC4 with Apache + with working xdebug (also using xdebug mode toggle script from https://github.com/lando/lando/issues/1668#issuecomment-772829423):

.lando.yml

```
name: drupal1083
recipe: drupal10
config:
  webroot: web
  php: '8.2' # Fake the version to prevent Lando errors but the correct version will be set in a custom image.
  database: mysql:8.0
  xdebug: off
  composer_version: '2'
  config:
    php: .lando/php.ini

services:
  appserver:
    scanner: false
    overrides:
      image: 'custom/php:8.3.0RC4-apache-bullseye'
      build: ./.lando/php
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_MODE:

  database:
    creds:
      user: drupal1083
      password: drupal1083
      database: drupal1083

  phpmyadmin:
    scanner: false
    type: phpmyadmin:5.1
    hosts:
      - database

proxy:
  appserver:
    - drupal1083.localhost
  phpmyadmin:
    - pma.drupal1083.localhost

tooling:
  xdebug:
    description: Loads Xdebug in the selected mode.
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root
```

.lando/php/Dockerfile

```
# docker build -t custom/php:8.3.0RC4-apache-bullseye .

FROM php:8.3.0RC4-apache-bullseye

# Install dependencies we need
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man7 \
  && apt -y update && apt-get install -y \
    gnupg2 \
    wget \
  && echo 'deb http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main' >> /etc/apt/sources.list.d/pgdg.list \
  && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
  && apt-get update && apt-get install -y \
    bzip2 \
    default-mysql-client \
    exiftool \
    git-core \
    imagemagick \
    libbz2-dev \
    libc-client-dev \
    libfreetype6-dev \
    libicu-dev \
    libjpeg62-turbo-dev \
    libkrb5-dev \
    libldap2-dev \
    libmagickwand-dev \
    libmemcached-dev \
    libpng-dev \
    libpq-dev \
    libssl-dev \
    libwebp-dev \
    libxml2-dev \
    libzip-dev \
    libonig-dev \
    openssl \
    postgresql-client-10 \
    pv \
    rsync \
    ssh \
    unzip \
    wget \
    xfonts-75dpi \
    xfonts-base \
    zlib1g-dev

RUN pecl install apcu \
  && pecl install imagick \
  && pecl install memcached \
  && pecl install oauth \
  && pecl install redis-5.3.7 \
#  && pecl install xdebug \
  && docker-php-ext-configure ldap --with-libdir=lib/$(uname -m)-linux-gnu/ \
  && docker-php-ext-enable apcu \
  && docker-php-ext-enable imagick \
  && docker-php-ext-enable memcached \
  && docker-php-ext-enable oauth \
  && docker-php-ext-enable redis \
  && docker-php-ext-install bcmath \
  && docker-php-ext-install bz2 \
  && docker-php-ext-install calendar \
  && docker-php-ext-install exif \
  && docker-php-ext-install gettext \
  && docker-php-ext-install intl \
  && docker-php-ext-install ldap \
  && docker-php-ext-install mbstring \
  && docker-php-ext-install mysqli \
  && docker-php-ext-install opcache \
  && docker-php-ext-install pcntl \
  && docker-php-ext-install pdo \
  && docker-php-ext-install pdo_mysql \
  && docker-php-ext-install pdo_pgsql \
  && docker-php-ext-install soap \
  && docker-php-ext-install zip \
  && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
  && php composer-setup.php --install-dir=/usr/local/bin --filename=composer --version=2.2.18 \
  && php -r "unlink('composer-setup.php');" \
  && chsh -s /bin/bash www-data && mkdir -p /var/www/.composer && chown -R www-data:www-data /var/www \
  && apt-get -y clean \
  && apt-get -y autoclean \
  && apt-get -y autoremove \
  && rm -rf /var/lib/apt/lists/* && rm -rf && rm -rf /var/lib/cache/* && rm -rf /var/lib/log/* && rm -rf /tmp/* \
  && PHP_OPENSSL=yes docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
  && docker-php-ext-install imap \
  && docker-php-ext-configure gd --enable-gd --with-jpeg --with-webp --with-freetype \
  && docker-php-ext-install gd

# While there's no xdebug release for PHP 8.3, we need to install it from source.
# As soon as we can install with PECL, remove this RUN and uncomment the previous 
# pecl install xdebug line.
RUN apt-get install -y git \
    && git clone https://github.com/xdebug/xdebug.git \
    && cd xdebug \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && cd .. \
    && docker-php-ext-enable xdebug

RUN curl https://dl.yarnpkg.com
```

.lando/php.ini

```
memory_limit = 256M

; Xdebug settings required for PhpStorm.
; https://github.com/lando/lando/issues/1668#issuecomment-772829423
xdebug.start_with_request = yes
xdebug.log_level=0
```

.lando/xdebug.sh
```
#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Xdebug has been turned off, please use the following syntax: 'lando xdebug <mode>'."
  echo "Valid modes: https://xdebug.org/docs/all_settings#mode."
  echo xdebug.mode = off > /usr/local/etc/php/conf.d/zzz-lando-xdebug.ini
  /etc/init.d/apache2 reload
else
  mode="$1"
  echo xdebug.mode = "$mode" > /usr/local/etc/php/conf.d/zzz-lando-xdebug.ini
  /etc/init.d/apache2 reload
  echo "Xdebug is loaded in "$mode" mode."
fi
```
